CREATE TABLE IF NOT EXISTS items (
    id VARCHAR[16] PRIMARY KEY,
    name TEXT NOT NULL,
    filename TEXT NOT NULL,
    type INT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 1024,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)