// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package db

import (
	"context"

	"uuid"
)

const createItem = `-- name: CreateItem :exec
INSERT INTO items (id, name, filename, type) VALUES (?, ?, ?, ?)
`

type CreateItemParams struct {
	ID       uuid.UUID
	Name     string
	Filename string
	Type     int
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Name,
		arg.Filename,
		arg.Type,
	)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, filename, type, "order", created FROM  items
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Filename,
			&i.Type,
			&i.Order,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, name, filename, type, "order", created FROM items WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Filename,
		&i.Type,
		&i.Order,
		&i.Created,
	)
	return i, err
}
