// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"uuid"
)

type Item struct {
	ID       uuid.UUID
	Name     string
	Filename string
	Type     int
	Order    int
	Created  time.Time
}
